### ISSUE TITLE
Open-Source=

### ISSUE THREAD

**Issue by Z4us** [nickdesaulniers/What-Open-Source-Means-To-Me#82]
A coöperative way to create #FreeSoftware having more value than the "Closed" (i.e. commercial) kinds

**Comment by reqshark** [comment]
+1

**Comment by justinclift** [comment]
@Z4us Want to turn this into a Pull Request on the main README.md?  (at the bottom btw :wink:)

**Comment by Z4us** [comment]
I never wrote a request to pull anywhere. Can you offer me a "How2", please? Would be highly appreciated; TIA.

**Comment by justinclift** [comment]
@Z4us Here's the Official How-To:

&nbsp; &nbsp;  https://help.github.com/articles/using-pull-requests/

In theory, that should take you through the whole process from start to finish.  Seems like the verbose/long-winded version of things, rather than just the key points... but it should give you good background info too, etc.

Let me know if it doesn't work for you, or if there's something a bit confusing in it. :grinning:

**Comment by nickdesaulniers** [comment]
overview:
1. Fork this repo
2. clone your fork
3. edit readme.md
4. commit your patch
5. push your patch to your fork
6. issue pull request

There's a 2a in there, which is create your own branch to work off of.

**Comment by justinclift** [comment]
@nickdesaulniers Your steps 2 and 5 can be skipped. GitHub's online editing for text files works pretty well. :smile:

**Comment by nickdesaulniers** [comment]
neat!

**Comment by reqshark** [comment]
ya @jellekralt, there's more than one way to skin an octocat. :octocat:  

generally it's easier to start out using the github web interface but all of it works just as well from the command line.

basically once you fork it, you can play around with it, but just remember it's got a special link back to the original, which comes into play during an ongoing Pull Request (PR). 

Anyway after you fork and push up some changes to it, if you like what you've done to your fork, you'll  [pull request button](https://help.github.com/articles/creating-a-pull-request/) from somewhere so that it opens the PR form interface like how you do on issues.

you don't have to create a branch, you can just push your changes to your fork's master branch, all that [branching stuff is a personal preference thing](http://nvie.com/posts/a-successful-git-branching-model/). 

and don't forget: you could always just delete your fork and fork it again if you mess up. same thing applies to anything you clone, just re-clone. that's sometimes easier than `rebase` IMO. before i knew how to use `git rebase` that's what i used to do when I needed to make corrections.

another interesting fact to keep in mind: once you issue a PR to someone's project from your fork, the state of your fork morphs into a new state that opens that special link back to the original. During any pending PR state, anytime you push new commits up your fork they will get reflected in the PR and that's how we can discuss and make more changes to the diff before it's merged!

**Comment by justinclift** [comment]
@Z4us Reminder ping... :wink:

**Comment by justinclift** [comment]
@Z4us Should I just close this? :wink:
